import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LeftSidebar from "@/components/shared/left-sidebar";
import Header from "@/components/shared/header";
import RightSidebar from "@/components/shared/right-sidebar";
import MobileNavbar from "@/components/shared/mobile-navbar";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aeko App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background`}
      >
        <ThemeProvider defaultTheme="dark" storageKey="aeko-theme">
          {/* Main container */}
          <div className="flex mx-auto">
            {/* Left sidebar */}
            <LeftSidebar />

            {/* Main content */}
            <main className="md:pl-[90px] xl:pl-[200px] xl:pr-[320px] flex-1 min-h-screen min-w-[600px] snap-y snap-mandatory">
              <Header />
              <div className="max-w-[600px] mx-auto py-4 px-6 snap-center">
                {children}
              </div>
            </main>
            {/* Right sidebar */}
            <RightSidebar />
          </div>
          {/* Mobile navbar */}
          <MobileNavbar />
        </ThemeProvider>
      </body>
    </html>
  );
}
