import { User } from "@/types/user";

export const MOCK_PROFILE: User = {
  botPreferences: {
    preferredSentiment: "neutral",
    topics: [],
    communicationStyle: "casual",
    responseLength: "medium",
  },
  botAnalytics: {
    totalInteractions: 0,
    averageResponseTime: 0,
    satisfactionRating: 5,
  },
  emailVerification: {
    isVerified: true,
    verificationCode: null,
    codeExpiresAt: null,
    codeAttempts: 0,
    lastCodeSent: "2025-11-17T06:24:33.481Z",
  },
  profileCompletion: {
    hasProfilePicture: false,
    hasBio: false,
    hasFollowers: false,
    hasWalletConnected: false,
    hasVerifiedEmail: true,
    completedAt: null,
    completionPercentage: 25,
  },
  onboarding: {
    interestsSelected: true,
    completed: false,
  },
  privacy: {
    isPrivate: false,
    allowFollowRequests: true,
    showOnlineStatus: true,
    allowDirectMessages: "everyone",
  },
  twoFactorAuth: {
    isEnabled: false,
    secret: null,
    enabledAt: null,
    lastUsed: null,
    backupCodes: [],
  },
  ownedCommunities: [],
  _id: "691abccd5af542c323756bcd",
  name: "Tola Thompson",
  username: "tolathompson",
  email: "maikmatt@outlook.com",
  oauthProvider: null,
  oauthId: null,
  avatar: "",
  lastLoginAt: null,
  profilePicture: "/users/sarah-johnson.jpeg",
  bio: "Philanthropist, Wife, Mother of 3, just here to connect with friends",
  followers: Array(2800).fill("1"), // Mocking 2.8K
  following: Array(200).fill("1"), // Mocking 200
  posts: [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "31",
    "32",
    "33",
    "34",
    "35",
    "36",
    "37",
    "38",
    "39",
    "40",
    "41",
    "42",
    "43",
    "44",
    "45",
    "46",
  ], // Mocking length to match design (46)
  aekoBalance: 0,
  blueTick: false,
  goldenTick: false,
  subscriptionStatus: "inactive",
  subscriptionExpiry: null,
  banned: false,
  isAdmin: false,
  botEnabled: false,
  botPersonality: "friendly",
  botResponses: [],
  interests: ["691de023193fe01e3a7742cb", "691de043193fe01e3a7742cf"],
  createdAt: "2025-11-17T06:12:29.176Z",
  updatedAt: "2025-11-27T07:11:27.735Z",
  __v: 0,
  communities: [],
  followingCommunities: [],
  communityMemberships: [],
  blockedUsers: [],
  followRequests: [],
};
